set_device -family {PolarFireSoC} -die {MPFS250TS} -speed {-1} -range {IND}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/CORERESET/CORERESET_0/core/corereset_pf.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/CORERESET/CORERESET.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/CORERESET_PF_C1/CORERESET_PF_C1_0/core/corereset_pf.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/CORERESET_PF_C1/CORERESET_PF_C1.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/CORERESET_PF_C2/CORERESET_PF_C2_0/core/corereset_pf.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/CORERESET_PF_C2/CORERESET_PF_C2.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/CORERESET_PF_C5/CORERESET_PF_C5_0/core/corereset_pf.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/CORERESET_PF_C5/CORERESET_PF_C5.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/INIT_MONITOR/INIT_MONITOR_0/INIT_MONITOR_INIT_MONITOR_0_PFSOC_INIT_MONITOR.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/INIT_MONITOR/INIT_MONITOR.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_CCC_C0/PF_CCC_C0_0/PF_CCC_C0_PF_CCC_C0_0_PF_CCC.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_CCC_C0/PF_CCC_C0.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_CLK_DIV_C0/PF_CLK_DIV_C0_0/PF_CLK_DIV_C0_PF_CLK_DIV_C0_0_PF_CLK_DIV.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_CLK_DIV_C0/PF_CLK_DIV_C0.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_OSC_C0/PF_OSC_C0_0/PF_OSC_C0_PF_OSC_C0_0_PF_OSC.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_OSC_C0/PF_OSC_C0.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_XCVR_REF_CLK_C0/PF_XCVR_REF_CLK_C0_0/PF_XCVR_REF_CLK_C0_PF_XCVR_REF_CLK_C0_0_PF_XCVR_REF_CLK.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_XCVR_REF_CLK_C0/PF_XCVR_REF_CLK_C0.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/CLOCKS_AND_RESETS/CLOCKS_AND_RESETS.v}
read_verilog -mode system_verilog -lib COREAPB3_LIB {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/CoreAPB3/4.2.100/rtl/vlog/core/coreapb3_muxptob3.v}
read_verilog -mode system_verilog -lib COREAPB3_LIB {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/CoreAPB3/4.2.100/rtl/vlog/core/coreapb3_iaddr_reg.v}
read_verilog -mode system_verilog -lib COREAPB3_LIB {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/CoreAPB3/4.2.100/rtl/vlog/core/coreapb3.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/CoreAPB3_C0/CoreAPB3_C0.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/FIC_CONVERTER/FIC_CONVERTER.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/MSS_VIDEO_KIT_H264/MSS_VIDEO_KIT_H264.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0/CCC_0/PF_DDR4_C0_CCC_0_PF_CCC.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_ACT_N/PF_DDR4_C0_DDRPHY_BLK_IOD_ACT_N_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_A_11_0/PF_DDR4_C0_DDRPHY_BLK_IOD_A_11_0_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_A_12/PF_DDR4_C0_DDRPHY_BLK_IOD_A_12_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_A_13/PF_DDR4_C0_DDRPHY_BLK_IOD_A_13_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_BA/PF_DDR4_C0_DDRPHY_BLK_IOD_BA_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_BCLK_TRAINING/PF_DDR4_C0_DDRPHY_BLK_IOD_BCLK_TRAINING_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_BG/PF_DDR4_C0_DDRPHY_BLK_IOD_BG_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_CAS_N/PF_DDR4_C0_DDRPHY_BLK_IOD_CAS_N_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_CKE/PF_DDR4_C0_DDRPHY_BLK_IOD_CKE_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_CS_N/PF_DDR4_C0_DDRPHY_BLK_IOD_CS_N_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_ODT/PF_DDR4_C0_DDRPHY_BLK_IOD_ODT_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_RAS_N/PF_DDR4_C0_DDRPHY_BLK_IOD_RAS_N_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_REF_CLK_TRAINING/PF_DDR4_C0_DDRPHY_BLK_IOD_REF_CLK_TRAINING_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_RESET_N/PF_DDR4_C0_DDRPHY_BLK_IOD_RESET_N_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_WE_N/PF_DDR4_C0_DDRPHY_BLK_IOD_WE_N_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/LANECTRL_ADDR_CMD_0/PF_LANECTRL_PAUSE_SYNC.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/LANECTRL_ADDR_CMD_0/PF_DDR4_C0_DDRPHY_BLK_LANECTRL_ADDR_CMD_0_PF_LANECTRL.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_0_CTRL/PF_LANECTRL_PAUSE_SYNC.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_0_CTRL/PF_DDR4_C0_DDRPHY_BLK_LANE_0_CTRL_PF_LANECTRL.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_0_IOD_DM/PF_DDR4_C0_DDRPHY_BLK_LANE_0_IOD_DM_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_0_IOD_DQSW_TRAINING/PF_DDR4_C0_DDRPHY_BLK_LANE_0_IOD_DQSW_TRAINING_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_0_IOD_DQS/PF_DDR4_C0_DDRPHY_BLK_LANE_0_IOD_DQS_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_0_IOD_DQ/PF_DDR4_C0_DDRPHY_BLK_LANE_0_IOD_DQ_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_0_IOD_READ_TRAINING/PF_DDR4_C0_DDRPHY_BLK_LANE_0_IOD_READ_TRAINING_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_1_CTRL/PF_LANECTRL_PAUSE_SYNC.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_1_CTRL/PF_DDR4_C0_DDRPHY_BLK_LANE_1_CTRL_PF_LANECTRL.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_1_IOD_DM/PF_DDR4_C0_DDRPHY_BLK_LANE_1_IOD_DM_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_1_IOD_DQSW_TRAINING/PF_DDR4_C0_DDRPHY_BLK_LANE_1_IOD_DQSW_TRAINING_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_1_IOD_DQS/PF_DDR4_C0_DDRPHY_BLK_LANE_1_IOD_DQS_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_1_IOD_DQ/PF_DDR4_C0_DDRPHY_BLK_LANE_1_IOD_DQ_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_1_IOD_READ_TRAINING/PF_DDR4_C0_DDRPHY_BLK_LANE_1_IOD_READ_TRAINING_PF_IOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/ddr_init_iterator.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/ram_simple_dp.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/FIFO_BLK.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/LANE_CTRL.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/LANE_ALIGNMENT.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/APB_IF.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/DLL_MON.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/flag_generator.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/trn_bclksclk.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/trn_cmdaddr.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/trn_dqsw.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/TRN_CLK.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/ddr4_vref.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/DELAY_CTRL.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/APB_IOG_CTRL_SM.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/IOG_IF.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/dq_align_dqs_optimization.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/gate_training.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/RDLVL_TRAIN.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/RDLVL_SMS.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/RDLVL.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/TRN_COMPLETE.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/VREF_TR.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/WRLVL_BOT.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/WRLVL.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/LEVELLING.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/PHY_SIG_MOD.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/write_callibrator.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/TIP_CTRL_BLK.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/register_bank.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/CoreDDR_TIP_INT.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/CoreDDR_TIP_SYN.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0_DDRPHY_BLK/PF_DDR4_C0_DDRPHY_BLK.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0/DLL_0/PF_DDR4_C0_DLL_0_PF_CCC.v}
 add_include_path  {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0/DDRCTRL_0}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0/DDRCTRL_0/CoreDDRMemCtrlr_0.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Actel/SgCore/PF_DDR_CFG_INIT/1.0.100/cfg_init.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0/PF_DDR4_C0.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/AXI4_M_M_IF.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/AXI4_S_IF.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_corefifo_NstagesSync.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_corefifo_grayToBinConv.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_corefifo_async.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_corefifo_resetSync.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_corefifo_sync.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_corefifo_fwft.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_corefifo_sync_scntr.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_LSRAM_top.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_ram_wrapper.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/video_axi_fifo.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/ddr_rw_arbiter.v}
read_vhdl -mode vhdl_2008 {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/write_mux.vhd}
read_vhdl -mode vhdl_2008 {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/request_scheduler.vhd}
read_vhdl -mode vhdl_2008 {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/write_demux.vhd}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/write_top.v}
read_vhdl -mode vhdl_2008 {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/read_demux.vhd}
read_vhdl -mode vhdl_2008 {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/read_mux.vhd}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/read_top.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/DDR_AXI4_ARBITER_PF_Native.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/DDR_AXI4_ARBITER_PF.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/DDR_AXI4_ARBITER_PF_C0/DDR_AXI4_ARBITER_PF_C0.v}
read_vhdl -mode vhdl_2008 {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/hdl/data_packer.vhd}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/hdl/ddr_write_controller_enc.v}
read_vhdl -mode vhdl_2008 {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/hdl/ram2port.vhd}
read_vhdl -mode vhdl_2008 {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/hdl/video_fifo.vhd}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/DDR_WRITE_JPEG/DDR_WRITE_JPEG.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/script_support/hdl/JPEG_WRITE/apb_wrapper.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/script_support/hdl/JPEG_WRITE/jls_encoder.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/script_support/hdl/JPEG_WRITE/jpeg_control_fsm.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/hdl/jpeg_top.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/script_support/hdl/JPEG_WRITE/ram8bit_input.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/top_ddr_write/top_ddr_write.v}
read_verilog -mode system_verilog {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/VKPFSOC_TOP/VKPFSOC_TOP.v}
set_top_level {VKPFSOC_TOP}
read_sdc -component {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/MSS_VIDEO_KIT_H264/MSS_VIDEO_KIT_H264.sdc}
read_sdc -component {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0/DLL_0/PF_DDR4_C0_DLL_0_PF_CCC.sdc}
read_sdc -component {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0/PF_DDR4_C0.sdc}
read_sdc -component {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0/CCC_0/PF_DDR4_C0_CCC_0_PF_CCC.sdc}
read_sdc -component {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_CLK_DIV_C0/PF_CLK_DIV_C0_0/PF_CLK_DIV_C0_PF_CLK_DIV_C0_0_PF_CLK_DIV.sdc}
read_sdc -component {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_CCC_C0/PF_CCC_C0_0/PF_CCC_C0_PF_CCC_C0_0_PF_CCC.sdc}
derive_constraints
write_sdc {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/constraint/VKPFSOC_TOP_derived_constraints.sdc}
write_ndc {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/constraint/VKPFSOC_TOP_derived_constraints.ndc}
write_pdc {/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/constraint/fp/VKPFSOC_TOP_derived_constraints.pdc}
