# Microchip Technology Inc.
# Date: 2026-Jun-22 13:36:00
# This file was generated based on the following SDC source files:
#   /home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_CCC_C0/PF_CCC_C0_0/PF_CCC_C0_PF_CCC_C0_0_PF_CCC.sdc
#   /home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_CLK_DIV_C0/PF_CLK_DIV_C0_0/PF_CLK_DIV_C0_PF_CLK_DIV_C0_0_PF_CLK_DIV.sdc
#   /home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/MSS_VIDEO_KIT_H264/MSS_VIDEO_KIT_H264.sdc
#   /home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0/PF_DDR4_C0.sdc
#   /home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0/CCC_0/PF_DDR4_C0_CCC_0_PF_CCC.sdc
#   /home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design_READ_WRITE/VKPFSOC_JPEG_WRITE/component/work/PF_DDR4_C0/DLL_0/PF_DDR4_C0_DLL_0_PF_CCC.sdc
#   /home/ahlemzenache/microchip/Libero_SoC_2025.1/Libero_SoC/Designer/data/aPA5M/cores/constraints/IND/osc_rc2mhz.sdc
# *** Any modifications to this file will be lost if derived constraints is re-run. ***
#

create_clock -name {REF_CLK_PAD_P} -period 6.73401 [ get_ports { REF_CLK_PAD_P } ]
create_clock -name {osc_rc2mhz} -period 469.48 [ get_pins { CLOCKS_AND_RESETS_inst_0/PF_OSC_C0_0/PF_OSC_C0_0/I_OSC_2/CLK } ]
create_generated_clock -name {CLOCKS_AND_RESETS_inst_0/PF_CCC_C0_0/PF_CCC_C0_0/pll_inst_0/OUT0} -multiply_by 2693603 -divide_by 3200000 -source [ get_pins { CLOCKS_AND_RESETS_inst_0/PF_CCC_C0_0/PF_CCC_C0_0/pll_inst_0/REF_CLK_0 } ] -phase 0 [ get_pins { CLOCKS_AND_RESETS_inst_0/PF_CCC_C0_0/PF_CCC_C0_0/pll_inst_0/OUT0 } ]
create_generated_clock -name {CLOCKS_AND_RESETS_inst_0/PF_CCC_C0_0/PF_CCC_C0_0/pll_inst_0/OUT1} -multiply_by 2693603 -divide_by 8000000 -source [ get_pins { CLOCKS_AND_RESETS_inst_0/PF_CCC_C0_0/PF_CCC_C0_0/pll_inst_0/REF_CLK_0 } ] -phase 0 [ get_pins { CLOCKS_AND_RESETS_inst_0/PF_CCC_C0_0/PF_CCC_C0_0/pll_inst_0/OUT1 } ]
create_generated_clock -name {CLOCKS_AND_RESETS_inst_0/PF_CCC_C0_0/PF_CCC_C0_0/pll_inst_0/OUT2} -multiply_by 2693603 -divide_by 2000000 -source [ get_pins { CLOCKS_AND_RESETS_inst_0/PF_CCC_C0_0/PF_CCC_C0_0/pll_inst_0/REF_CLK_0 } ] -phase 0 [ get_pins { CLOCKS_AND_RESETS_inst_0/PF_CCC_C0_0/PF_CCC_C0_0/pll_inst_0/OUT2 } ]
create_generated_clock -name {PF_DDR4_C0_0/CCC_0/pll_inst_0/OUT0} -multiply_by 4 -source [ get_pins { PF_DDR4_C0_0/CCC_0/pll_inst_0/REF_CLK_0 } ] -phase 0 [ get_pins { PF_DDR4_C0_0/CCC_0/pll_inst_0/OUT0 } ]
create_generated_clock -name {PF_DDR4_C0_0/CCC_0/pll_inst_0/OUT1} -divide_by 1 -source [ get_pins { PF_DDR4_C0_0/CCC_0/pll_inst_0/REF_CLK_0 } ] -phase 0 [ get_pins { PF_DDR4_C0_0/CCC_0/pll_inst_0/OUT1 } ]
create_generated_clock -name {PF_DDR4_C0_0/CCC_0/pll_inst_0/OUT2} -multiply_by 4 -source [ get_pins { PF_DDR4_C0_0/CCC_0/pll_inst_0/REF_CLK_0 } ] -phase 0 [ get_pins { PF_DDR4_C0_0/CCC_0/pll_inst_0/OUT2 } ]
create_generated_clock -name {PF_DDR4_C0_0/CCC_0/pll_inst_0/OUT3} -multiply_by 4 -source [ get_pins { PF_DDR4_C0_0/CCC_0/pll_inst_0/REF_CLK_0 } ] -phase 0 [ get_pins { PF_DDR4_C0_0/CCC_0/pll_inst_0/OUT3 } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/*/I_IOD_*/ARST_N } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_*_CTRL/I_LANECTRL/HS_IO_CLK_PAUSE } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANECTRL_ADDR_CMD_0/I_LANECTRL*/HS_IO_CLK_PAUSE } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/*/I_IOD_*/RX_SYNC_RST* } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/*/I_IOD_*/DELAY_LINE_MOVE } ]
set_false_path -through [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/*/I_IOD_*/DELAY_LINE_OUT_OF_RANGE } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DDR_READ } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/RESET } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DELAY_LINE_DIRECTION } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DELAY_LINE_MOVE } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DELAY_LINE_LOAD PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DELAY_LINE_SEL } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/SWITCH } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/READ_CLK_SEL[2] } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DLL_CODE[0] } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DLL_CODE[1] } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DLL_CODE[2] } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DLL_CODE[3] } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DLL_CODE[4] } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DLL_CODE[5] } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DLL_CODE[6] } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DLL_CODE[7] } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DDR_READ } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/RESET } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DELAY_LINE_DIRECTION } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DELAY_LINE_MOVE } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DELAY_LINE_LOAD PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DELAY_LINE_SEL } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/SWITCH } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/READ_CLK_SEL[2] } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DLL_CODE[0] } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DLL_CODE[1] } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DLL_CODE[2] } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DLL_CODE[3] } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DLL_CODE[4] } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DLL_CODE[5] } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DLL_CODE[6] } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DLL_CODE[7] } ]
set_false_path -through [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/*/I_*FEEDBACK*/Y } ]
set_false_path -through [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/OB_DIFF_CK0/Y } ]
set_false_path -through [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/OB_A_12/Y } ]
set_false_path -through [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/*/I_TRIBUFF_*/D } ]
set_false_path -through [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/*/I_TRIBUFF_*/E } ]
set_false_path -through [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/*/I_BIBUF*/D } ]
set_false_path -through [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/*/I_BIBUF*/E } ]
set_false_path -through [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/*/I_BIBUF*/Y } ]
set_false_path -through [ get_pins { PF_DDR4_C0_0/DDRPHY_BLK_0/*/I_BIBUF_DIFF_DQS_*/YN } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/CCC_0/pll_inst_0/PHASE_OUT0_SEL } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/CCC_0/pll_inst_0/PHASE_OUT2_SEL } ]
set_false_path -to [ get_pins { PF_DDR4_C0_0/CCC_0/pll_inst_0/PHASE_OUT3_SEL } ]
set_multicycle_path -setup_only 2 -from [ get_cells { PF_DDR4_C0_0/DDRPHY_BLK_0/IOD_TRAINING_0/COREDDR_TIP_INT_U/TIP_CTRL_BLK/u_write_callibrator/select* } ]
