onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /DDR_WRITE_tb/apb_pin
add wave -noupdate /DDR_WRITE_tb/DDR_A
add wave -noupdate /DDR_WRITE_tb/DDR_ACT_N
add wave -noupdate /DDR_WRITE_tb/DDR_BA
add wave -noupdate /DDR_WRITE_tb/DDR_BG
add wave -noupdate /DDR_WRITE_tb/DDR_CAS_N
add wave -noupdate /DDR_WRITE_tb/DDR_RAS_N
add wave -noupdate /DDR_WRITE_tb/DDR_WE_N
add wave -noupdate /DDR_WRITE_tb/DDR_CKE_0
add wave -noupdate /DDR_WRITE_tb/DDR_CS_N
add wave -noupdate /DDR_WRITE_tb/DDR_CK0
add wave -noupdate /DDR_WRITE_tb/DDR_CK0_N
add wave -noupdate /DDR_WRITE_tb/DDR_ODT_0
add wave -noupdate /DDR_WRITE_tb/DDR_RESET_N_0
add wave -noupdate /DDR_WRITE_tb/DDR_SHIELD0
add wave -noupdate /DDR_WRITE_tb/DDR_SHIELD1
add wave -noupdate /DDR_WRITE_tb/DDR_DM_N
add wave -noupdate /DDR_WRITE_tb/DDR_DQ_0
add wave -noupdate /DDR_WRITE_tb/DDR_DQS_0
add wave -noupdate /DDR_WRITE_tb/DDR_DQS_N_0
add wave -noupdate /DDR_WRITE_tb/DDR4_MEM_ALERT_N
add wave -noupdate /DDR_WRITE_tb/apb_pin
add wave -noupdate /DDR_WRITE_tb/DDR_A
add wave -noupdate /DDR_WRITE_tb/DDR_ACT_N
add wave -noupdate /DDR_WRITE_tb/DDR_BA
add wave -noupdate /DDR_WRITE_tb/DDR_BG
add wave -noupdate /DDR_WRITE_tb/DDR_CAS_N
add wave -noupdate /DDR_WRITE_tb/DDR_RAS_N
add wave -noupdate /DDR_WRITE_tb/DDR_WE_N
add wave -noupdate /DDR_WRITE_tb/DDR_CKE_0
add wave -noupdate /DDR_WRITE_tb/DDR_CS_N
add wave -noupdate /DDR_WRITE_tb/DDR_CK0
add wave -noupdate /DDR_WRITE_tb/DDR_CK0_N
add wave -noupdate /DDR_WRITE_tb/DDR_ODT_0
add wave -noupdate /DDR_WRITE_tb/DDR_RESET_N_0
add wave -noupdate /DDR_WRITE_tb/DDR_SHIELD0
add wave -noupdate /DDR_WRITE_tb/DDR_SHIELD1
add wave -noupdate /DDR_WRITE_tb/DDR_DM_N
add wave -noupdate /DDR_WRITE_tb/DDR_DQ_0
add wave -noupdate /DDR_WRITE_tb/DDR_DQS_0
add wave -noupdate /DDR_WRITE_tb/DDR_DQS_N_0
add wave -noupdate /DDR_WRITE_tb/DDR4_MEM_ALERT_N
add wave -noupdate /DDR_WRITE_tb/DUT/VKPFSOC_TOP_0/CLOCKS_AND_RESETS_inst_0/CLK_50MHz
add wave -noupdate /DDR_WRITE_tb/DUT/VKPFSOC_TOP_0/CLOCKS_AND_RESETS_inst_0/REF_CLK_PAD_N
add wave -noupdate /DDR_WRITE_tb/DUT/VKPFSOC_TOP_0/CLOCKS_AND_RESETS_inst_0/REF_CLK_PAD_P
add wave -noupdate /DDR_WRITE_tb/DUT/VKPFSOC_TOP_0/CLOCKS_AND_RESETS_inst_0/PF_XCVR_REF_CLK_C0_0/FAB_REF_CLK
add wave -noupdate /DDR_WRITE_tb/DUT/VKPFSOC_TOP_0/CLOCKS_AND_RESETS_inst_0/PF_CCC_C0_0/OUT1_FABCLK_0
add wave -noupdate /DDR_WRITE_tb/DUT/VKPFSOC_TOP_0/CLOCKS_AND_RESETS_inst_0/PF_CCC_C0_0/OUT0_FABCLK_0
add wave -noupdate /DDR_WRITE_tb/DUT/VKPFSOC_TOP_0/CLOCKS_AND_RESETS_inst_0/PF_CCC_C0_0/PLL_LOCK_0
add wave -noupdate /DDR_WRITE_tb/DUT/VKPFSOC_TOP_0/CLOCKS_AND_RESETS_inst_0/PF_CCC_C0_0/REF_CLK_0
add wave -noupdate /DDR_WRITE_tb/DUT/VKPFSOC_TOP_0/CLOCKS_AND_RESETS_inst_0/AND3_0/A
add wave -noupdate /DDR_WRITE_tb/DUT/VKPFSOC_TOP_0/CLOCKS_AND_RESETS_inst_0/AND3_0/B
add wave -noupdate /DDR_WRITE_tb/DUT/VKPFSOC_TOP_0/CLOCKS_AND_RESETS_inst_0/AND3_0/C
add wave -noupdate /DDR_WRITE_tb/DUT/VKPFSOC_TOP_0/CLOCKS_AND_RESETS_inst_0/AND3_0/Y
add wave -noupdate /DDR_WRITE_tb/DUT/VKPFSOC_TOP_0/CLOCKS_AND_RESETS_inst_0/CORERESET_CLK_50MHz/FABRIC_RESET_N
add wave -noupdate /DDR_WRITE_tb/DUT/VKPFSOC_TOP_0/PF_DDR4_C0_0/CTRLR_READY
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {813554 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 581
configure wave -valuecolwidth 40
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {3088888 ps} {4993275 ps}
