onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_top_system/SYSCLK
add wave -noupdate /tb_top_system/NSYSRESET
add wave -noupdate /tb_top_system/psel
add wave -noupdate /tb_top_system/pwrite
add wave -noupdate /tb_top_system/paddr
add wave -noupdate /tb_top_system/pwdata
add wave -noupdate /tb_top_system/prdata
add wave -noupdate /tb_top_system/pready
add wave -noupdate /tb_top_system/apb_pin
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/read_en_i
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/read_done_i
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/frame_end_i
add wave -noupdate /tb_top_system/ddr_ctrl_ready_i
add wave -noupdate /tb_top_system/arready
add wave -noupdate /tb_top_system/awready
add wave -noupdate /tb_top_system/wready
add wave -noupdate /tb_top_system/rvalid
add wave -noupdate /tb_top_system/rlast
add wave -noupdate /tb_top_system/bvalid
add wave -noupdate /tb_top_system/rdata
add wave -noupdate /tb_top_system/rid
add wave -noupdate /tb_top_system/bid
add wave -noupdate /tb_top_system/rresp
add wave -noupdate /tb_top_system/bresp
add wave -noupdate /tb_top_system/araddr
add wave -noupdate /tb_top_system/awaddr
add wave -noupdate /tb_top_system/arvalid
add wave -noupdate /tb_top_system/awvalid
add wave -noupdate /tb_top_system/arid
add wave -noupdate /tb_top_system/awid
add wave -noupdate /tb_top_system/arlen
add wave -noupdate /tb_top_system/awlen
add wave -noupdate /tb_top_system/wdata
add wave -noupdate /tb_top_system/wvalid
add wave -noupdate /tb_top_system/wlast
add wave -noupdate /tb_top_system/bready
add wave -noupdate /tb_top_system/rready
add wave -noupdate /tb_top_system/frm_interrupt_o
add wave -noupdate /tb_top_system/axi_read_beats
add wave -noupdate /tb_top_system/axi_write_beats
add wave -noupdate /tb_top_system/axi_error
add wave -noupdate /tb_top_system/status_reg
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/data_unpacker_0/beats_to_read_o
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/data_unpacker_0/data_i
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/data_unpacker_0/data_o
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/data_unpacker_0/data_valid_o
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/data_unpacker_0/disp_clk_i
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/data_unpacker_0/fifo_data_valid_i
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/data_unpacker_0/fifo_read_o
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/data_unpacker_0/read_en_i
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/data_unpacker_0/reset_i
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/data_unpacker_0/resolution_i
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/aresetn_i
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/raempty_o
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/rclock_i
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/rdata_count
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/rdata_count_o
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/rdata_o
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/rdata_rdy_o
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/rempty_o
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/ren_i
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/reset_i
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/rhempty_o
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/wafull_o
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/wclock_i
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/wdata_count_o
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/wdata_i
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/wen_i
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/wfull_o
add wave -noupdate /tb_top_system/dut/DDR_Read_C0_0/DDR_Read_C0_0/genblk1/DDR_Read_Native_0/video_fifo_r/wresetn_i
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/clk
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/encoder_active_o
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/eof_flag
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/i_h
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/i_sof
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/i_sof_ps
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/i_w
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/i_x
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/i_e
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/near
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/o_data_pck
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/o_e_pck
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/o_last
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/o_last_flag
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/ram_data_valid
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/ram_read_data
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/rstn
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_fsm/sof_flag
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_jls/i_e
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_jls/i_h
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_jls/i_sof
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_jls/i_w
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_jls/i_x
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_jls/o_data
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_jls/o_e
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_jls/o_last
add wave -noupdate /tb_top_system/dut/jpeg_top_1/u_jls/rstn
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/data_packer_0/data_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/data_packer_0/data_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/data_packer_0/data_valid_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/data_packer_0/data_valid_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/data_packer_0/frame_end_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/data_packer_0/frame_end_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/data_packer_0/g_IP_DW
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/data_packer_0/g_OP_DW
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/data_packer_0/reset_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/data_packer_0/sys_clk_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/ddr_write_controller_enc_0/encoder_en_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/ddr_write_controller_enc_0/eof_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/ddr_write_controller_enc_0/fifo_count_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/ddr_write_controller_enc_0/fifo_reset_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/ddr_write_controller_enc_0/frame_ddr_addr_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/ddr_write_controller_enc_0/frm_interrupt_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/ddr_write_controller_enc_0/read_fifo_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/ddr_write_controller_enc_0/reset_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/ddr_write_controller_enc_0/sys_clk_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/ddr_write_controller_enc_0/wrclk_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/ddr_write_controller_enc_0/wrclk_reset_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/ddr_write_controller_enc_0/write_ackn_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/ddr_write_controller_enc_0/write_done_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/ddr_write_controller_enc_0/write_length_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/ddr_write_controller_enc_0/write_req_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/ddr_write_controller_enc_0/write_start_addr_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/g_HALF_EMPTY_THRESHOLD
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/g_INPUT_VIDEO_DATA_BIT_WIDTH
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/g_VIDEO_FIFO_AWIDTH
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/raempty_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/rclock_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/rdata_count_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/rdata_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/rdata_rdy_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/rempty_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/ren_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/rhempty_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/rresetn_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/wafull_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/wclock_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/wdata_count_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/wdata_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/wen_i
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/wfull_o
add wave -noupdate /tb_top_system/dut/DDR_WRITE_JPEG_0/video_fifo_0/wresetn_i
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {4445000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 532
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {4242121 ps} {5500867 ps}
