define_compile_point  -comment {Automatically Inserted}  {v:work.Intra420_luma_8s_1s} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.Intra420_chroma_8s} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.H264_Intra420_8s_1s} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.CAVLC_H264} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.H264_Iframe_Encoder_8s_1s_1s_22s} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.h264_top} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.mipi_csi2_rx_embsync_detect_Z12_layer0} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.mipi_csi2_rxdecoder_Z13_layer0} -type {hard}
define_compile_point  -comment {Automatically Inserted}  {v:work.IMX334_IF_TOP} -type {hard}
