quietly set ACTELLIBNAME PolarFireSoC
quietly set PROJECT_DIR "/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design (IMG_COMP_WRITE)/VKPFSOC_JPEG_WRITE"
#onerror { quit -f }
#onbreak { quit -f }
#source "${PROJECT_DIR}/simulation/bfmtovec_compile.tcl";
#source "${PROJECT_DIR}/simulation/MSS_VIDEO_KIT_H264_PFSOC_MSS_FIC0_compile_bfm.tcl";
#source "${PROJECT_DIR}/simulation/MSS_VIDEO_KIT_H264_PFSOC_MSS_FIC1_compile_bfm.tcl";
#source "${PROJECT_DIR}/simulation/MSS_VIDEO_KIT_H264_PFSOC_MSS_FIC3_compile_bfm.tcl";
#source "${PROJECT_DIR}/simulation/MSS_VIDEO_KIT_H264_PFSOC_MSS_FIC4_compile_bfm.tcl";


if {[file exists presynth/_info]} {
   echo "INFO: Simulation library presynth already exists"
} else {
   file delete -force presynth 
   vlib presynth
}
vmap presynth presynth
vmap polarfire "/home/ahlemzenache/microchip/Libero_SoC_2025.1/Libero_SoC/Designer/lib/modelsimpro/precompiled/vlog/polarfire"
vmap PolarFire "/home/ahlemzenache/microchip/Libero_SoC_2025.1/Libero_SoC/Designer/lib/modelsimpro/precompiled/vlog/polarfire"
if {[file exists COREAPB3_LIB/_info]} {
   echo "INFO: Simulation library COREAPB3_LIB already exists"
} else {
   file delete -force COREAPB3_LIB 
   vlib COREAPB3_LIB
}
vmap COREAPB3_LIB "COREAPB3_LIB"

vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/CORERESET/CORERESET_0/core/corereset_pf.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/CORERESET/CORERESET.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/CORERESET_PF_C0/CORERESET_PF_C0_0/core/corereset_pf.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/CORERESET_PF_C0/CORERESET_PF_C0.v"

vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/CORERESET_PF_C2/CORERESET_PF_C2_0/core/corereset_pf.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/CORERESET_PF_C2/CORERESET_PF_C2.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/CORERESET_PF_C1/CORERESET_PF_C1_0/core/corereset_pf.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/CORERESET_PF_C1/CORERESET_PF_C1.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/CORERESET_PF_C5/CORERESET_PF_C5_0/core/corereset_pf.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/CORERESET_PF_C5/CORERESET_PF_C5.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/INIT_MONITOR/INIT_MONITOR_0/INIT_MONITOR_INIT_MONITOR_0_PFSOC_INIT_MONITOR.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/INIT_MONITOR/INIT_MONITOR.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_CCC_C0/PF_CCC_C0_0/PF_CCC_C0_PF_CCC_C0_0_PF_CCC.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_CCC_C0/PF_CCC_C0.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_CLK_DIV_C0/PF_CLK_DIV_C0_0/PF_CLK_DIV_C0_PF_CLK_DIV_C0_0_PF_CLK_DIV.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_CLK_DIV_C0/PF_CLK_DIV_C0.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_OSC_C0/PF_OSC_C0_0/PF_OSC_C0_PF_OSC_C0_0_PF_OSC.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_OSC_C0/PF_OSC_C0.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_XCVR_REF_CLK_C0/PF_XCVR_REF_CLK_C0_0/PF_XCVR_REF_CLK_C0_PF_XCVR_REF_CLK_C0_0_PF_XCVR_REF_CLK.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_XCVR_REF_CLK_C0/PF_XCVR_REF_CLK_C0.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/CLOCKS_AND_RESETS/CLOCKS_AND_RESETS.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work COREAPB3_LIB "${PROJECT_DIR}/component/Actel/DirectCore/CoreAPB3/4.2.100/rtl/vlog/core/coreapb3_muxptob3.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work COREAPB3_LIB "${PROJECT_DIR}/component/Actel/DirectCore/CoreAPB3/4.2.100/rtl/vlog/core/coreapb3_iaddr_reg.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work COREAPB3_LIB "${PROJECT_DIR}/component/Actel/DirectCore/CoreAPB3/4.2.100/rtl/vlog/core/coreapb3.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/CoreAPB3_C0/CoreAPB3_C0.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/FIC_CONVERTER/FIC_CONVERTER.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/MSS_VIDEO_KIT_H264/MSS_BYP_NOBYP_BYP_BYP_BYP_syn_comps.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/MSS_VIDEO_KIT_H264/MSS_VIDEO_KIT_H264.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0/CCC_0/PF_DDR4_C0_CCC_0_PF_CCC.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_ACT_N/PF_DDR4_C0_DDRPHY_BLK_IOD_ACT_N_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_A_11_0/PF_DDR4_C0_DDRPHY_BLK_IOD_A_11_0_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_A_12/PF_DDR4_C0_DDRPHY_BLK_IOD_A_12_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_A_13/PF_DDR4_C0_DDRPHY_BLK_IOD_A_13_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_BA/PF_DDR4_C0_DDRPHY_BLK_IOD_BA_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_BCLK_TRAINING/PF_DDR4_C0_DDRPHY_BLK_IOD_BCLK_TRAINING_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_BG/PF_DDR4_C0_DDRPHY_BLK_IOD_BG_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_CAS_N/PF_DDR4_C0_DDRPHY_BLK_IOD_CAS_N_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_CKE/PF_DDR4_C0_DDRPHY_BLK_IOD_CKE_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_CS_N/PF_DDR4_C0_DDRPHY_BLK_IOD_CS_N_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_ODT/PF_DDR4_C0_DDRPHY_BLK_IOD_ODT_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_RAS_N/PF_DDR4_C0_DDRPHY_BLK_IOD_RAS_N_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_REF_CLK_TRAINING/PF_DDR4_C0_DDRPHY_BLK_IOD_REF_CLK_TRAINING_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_RESET_N/PF_DDR4_C0_DDRPHY_BLK_IOD_RESET_N_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/IOD_WE_N/PF_DDR4_C0_DDRPHY_BLK_IOD_WE_N_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/LANECTRL_ADDR_CMD_0/PF_LANECTRL_PAUSE_SYNC.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/LANECTRL_ADDR_CMD_0/PF_DDR4_C0_DDRPHY_BLK_LANECTRL_ADDR_CMD_0_PF_LANECTRL.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_0_CTRL/PF_LANECTRL_PAUSE_SYNC.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_0_CTRL/PF_DDR4_C0_DDRPHY_BLK_LANE_0_CTRL_PF_LANECTRL.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_0_IOD_DM/PF_DDR4_C0_DDRPHY_BLK_LANE_0_IOD_DM_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_0_IOD_DQSW_TRAINING/PF_DDR4_C0_DDRPHY_BLK_LANE_0_IOD_DQSW_TRAINING_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_0_IOD_DQS/PF_DDR4_C0_DDRPHY_BLK_LANE_0_IOD_DQS_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_0_IOD_DQ/PF_DDR4_C0_DDRPHY_BLK_LANE_0_IOD_DQ_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_0_IOD_READ_TRAINING/PF_DDR4_C0_DDRPHY_BLK_LANE_0_IOD_READ_TRAINING_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_1_CTRL/PF_LANECTRL_PAUSE_SYNC.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_1_CTRL/PF_DDR4_C0_DDRPHY_BLK_LANE_1_CTRL_PF_LANECTRL.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_1_IOD_DM/PF_DDR4_C0_DDRPHY_BLK_LANE_1_IOD_DM_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_1_IOD_DQSW_TRAINING/PF_DDR4_C0_DDRPHY_BLK_LANE_1_IOD_DQSW_TRAINING_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_1_IOD_DQS/PF_DDR4_C0_DDRPHY_BLK_LANE_1_IOD_DQS_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_1_IOD_DQ/PF_DDR4_C0_DDRPHY_BLK_LANE_1_IOD_DQ_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/LANE_1_IOD_READ_TRAINING/PF_DDR4_C0_DDRPHY_BLK_LANE_1_IOD_READ_TRAINING_PF_IOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/ddr_init_iterator.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/ram_simple_dp.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/FIFO_BLK.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/LANE_CTRL.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/LANE_ALIGNMENT.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/APB_IF.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/DLL_MON.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/flag_generator.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/trn_bclksclk.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/trn_cmdaddr.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/trn_dqsw.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/TRN_CLK.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/ddr4_vref.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/DELAY_CTRL.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/APB_IOG_CTRL_SM.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/IOG_IF.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/dq_align_dqs_optimization.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/gate_training.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/RDLVL_TRAIN.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/RDLVL_SMS.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/RDLVL.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/TRN_COMPLETE.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/VREF_TR.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/WRLVL_BOT.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/WRLVL.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/LEVELLING.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/PHY_SIG_MOD.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/write_callibrator.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/TIP_CTRL_BLK.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/register_bank.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/CoreDDR_TIP_INT.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/ddr_no_training.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/OE_GLUE_LOGIC.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/COREDDR_TIP/2.2.100/rtl/vlog/core/CoreDDR_TIP_SIM.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0_DDRPHY_BLK/PF_DDR4_C0_DDRPHY_BLK.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0/DLL_0/PF_DDR4_C0_DLL_0_PF_CCC.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0/CoreDDRMemCtrlr_0.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Actel/SgCore/PF_DDR_CFG_INIT/1.0.100/cfg_init.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/PF_DDR4_C0/PF_DDR4_C0.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/AXI4_M_M_IF.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/AXI4_S_IF.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_corefifo_NstagesSync.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_corefifo_grayToBinConv.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_corefifo_async.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_corefifo_resetSync.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_corefifo_sync.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_corefifo_fwft.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_corefifo_sync_scntr.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_LSRAM_top.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/axi_lbus_ram_wrapper.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/video_axi_fifo.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/ddr_rw_arbiter.v"
vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/write_mux.vhd"
vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/request_scheduler.vhd"
vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/write_demux.vhd"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/write_top.v"
vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/read_demux.vhd"
vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/read_mux.vhd"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/read_top.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/DDR_AXI4_ARBITER_PF_Native.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/Microchip/SolutionCore/DDR_AXI4_ARBITER_PF/2.2.0/RTL/DDR_AXI4_ARBITER_PF.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/DDR_AXI4_ARBITER_PF_C0/DDR_AXI4_ARBITER_PF_C0.v"
vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/hdl/data_packer.vhd"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/hdl/ddr_write_controller_enc.v"
vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/hdl/ram2port.vhd"
vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/hdl/video_fifo.vhd"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/DDR_WRITE_JPEG/DDR_WRITE_JPEG.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design (IMG_COMP_WRITE)/script_support/hdl/JPEG_WRITE/apb_wrapper.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design (IMG_COMP_WRITE)/script_support/hdl/JPEG_WRITE/jls_encoder.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design (IMG_COMP_WRITE)/script_support/hdl/JPEG_WRITE/jpeg_control_fsm.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/hdl/jpeg_top.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "/home/ahlemzenache/Documents/polarfire-soc-video-kit-reference-design (IMG_COMP_WRITE)/script_support/hdl/JPEG_WRITE/ram8bit_input.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/top_ddr_write/top_ddr_write.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" -sv -work presynth "${PROJECT_DIR}/component/work/VKPFSOC_TOP/VKPFSOC_TOP.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" "+incdir+${PROJECT_DIR}/component/Actel/Simulation/CLK_GEN/1.0.1" "+incdir+${PROJECT_DIR}/component/work/CLK_GEN_C0" "+incdir+${PROJECT_DIR}/component/work/ddr_write" -sv -work presynth "${PROJECT_DIR}/component/Actel/Simulation/CLK_GEN/1.0.1/CLK_GEN.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" "+incdir+${PROJECT_DIR}/component/Actel/Simulation/CLK_GEN/1.0.1" "+incdir+${PROJECT_DIR}/component/work/CLK_GEN_C0" "+incdir+${PROJECT_DIR}/component/work/ddr_write" -sv -work presynth "${PROJECT_DIR}/component/work/CLK_GEN_C0/CLK_GEN_C0.v"
vlog "+incdir+${PROJECT_DIR}/component/work/PF_DDR4_C0/DDRCTRL_0" "+incdir+${PROJECT_DIR}/component/Actel/Simulation/CLK_GEN/1.0.1" "+incdir+${PROJECT_DIR}/component/work/CLK_GEN_C0" "+incdir+${PROJECT_DIR}/component/work/ddr_write" -sv -work presynth "${PROJECT_DIR}/component/work/ddr_write/ddr_write.v"

vlog  -sv -work presynth "${PROJECT_DIR}/stimulus/arch_package.sv"
vlog  -sv -work presynth "${PROJECT_DIR}/stimulus/interface.sv"
vlog  -sv -work presynth "${PROJECT_DIR}/stimulus/ddr4.sv"
#vcom -2008 -explicit  -work presynth "${PROJECT_DIR}/stimulus/ddr_write1.v"

vlog "+incdir+${PROJECT_DIR}/stimulus" -sv -work presynth "${PROJECT_DIR}/stimulus/ddr_write1.v"
#vsim -voptargs=+acc presynth.DDR_WRITE_tb

vsim -L polarfire -L presynth -L COREAPB3_LIB  -t 1ps -pli /home/ahlemzenache/microchip/Libero_SoC_2025.1/Libero_SoC/Designer/lib/modelsimpro/pli/pf_crypto_lin_me_pli.so presynth.DDR_WRITE_tb
add wave /DDR_WRITE_tb/*
run 1000ns
log /DDR_WRITE_tb/*
#exit
